### ISSUE TITLE
Always get "Incorrect API format" as response

### ISSUE THREAD

**Issue by rrbaptista** [BMSVieira/osticket-api#10]
I'm trying to use this project on my osTicket installation, but i'm struggling to make it work.

I want to fetch data with a script written in R, using the jsonlite and httr libraries, but i'm not sure what's going wrong that keeps returning this: 

``
"{\"status\":\"Error\",\"data\":\"Incorrect API Format\"}"
``

Here's my code:

```
library(jsonlite)
library(httr)

header_api <- c('apikey' = 'my_api_key')

call <- VERB(verb = "GET", 
                url = "https://url_to_my_osticket_root/upload/ost_wbs/", 
                config = add_headers(header_api), 
                body = '{
                        "query":"ticket",
                        "condition":"all",
                        "sort": "status",
                        "parameters":{
                            "status":0
                            }
                        }')

convert_rawdata <- content(call, "text")

```

Am I missing something? What "Incorrect API format" means? I'm passing the API key in the header as a string, following the documentation instructions. 

I will be happy if someone helps me on this. Thanks!

**Comment by BMSVieira** [comment]
Hey, how are you?

_**Incorrect API format**_ means that you sent something wrong in the API key.

Recently i had people reaching out with the same problem.
Turns out some hosts capitalize Header variables.

The code is expecting a "apikey" but your server returns a "Apikey"... thats why it is always returning "Incorrect API Format" because it is empty.

Go to index.php >Line 29 and change it to:

` $key = array("apikey" => getallheaders()["Apikey"]);`

Give it a try!

**Comment by rrbaptista** [comment]
Hello @BMSVieira 

This error is happening with this line of code. 

Tried to pass "Apikey" on the code, to test if matches with the server response, but it doesn't work. 

Tried the pull request suggestion from @Nexis81, that tries to fix the lower/uppercase issues, got the same error.

**Comment by Nexis81** [comment]
The api check part of the code may need to be rewritten to account for how various hosts handle headers. Some capitalize, some don't. The api needs to be able to account for that.

**Comment by BMSVieira** [comment]
@Nexis81 Agreed! I am already working on that.

@ex0ticOne Can you try with Postman to see if there's something wrong with your code?

**Comment by rrbaptista** [comment]
@BMSVieira tried with Postman and I got the same response with my R coding.

**Comment by BMSVieira** [comment]
@Nexis81 fixed in the latest commit.
