### ISSUE TITLE
Can't view query on specific ticket but can view ticket by status

### ISSUE THREAD

**Issue by F4izal** [BMSVieira/osticket-api#4]
I trying ost_wbs on the root osticket installation and configire config for database and premises table but i trying access query for detial specific ticket by ID/Ticket number not work.

My osticket trying version 
V latest version fail
V.15.4.4 fail
V.15.3.1 fail

So you can help me please...?

**Comment by Nexis81** [comment]
There's an error in the ticket class file. There's a pull request to fix it.

**Comment by BMSVieira** [comment]
Sorry for late response, merged. 
Thank you!
